config/routes.rb
Dojo::Application.routes.draw do
  resources :katas

  match "/feedback" => "feedback#create"

  match "/auth/:provider/callback" => "auth#create"
  match "/signout" => "auth#destroy"

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root :to => 'katas#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def symbolize_keys(hash)
    Hash[hash.map {|k,v| [k.to_sym, v]}]
  end

end

app/controllers/auth_controller.rb
require 'dojo/repositories/repository'

class AuthController < AuthorizedController

  def create
    auth_hash = request.env['omniauth.auth']
    user = repo.find_by_uid( auth_hash[:uid], auth_hash[:provider] ).first
    user ||= create_user( auth_hash )
    session[:user_id] = user.id
    redirect_to katas_path
  end

  def destroy
    session[:user_id] = nil
    render :signout
  end

  private

  def repo
    Dojo::Repository.user
  end

  def create_user( authhash )
    data = { name:      authhash[:info][:name],
             email:     authhash[:info][:email],
             uid:       authhash[:uid],
             provider:  authhash[:provider] }
    repo.save( repo.new( data ))
  end

end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_filter :authenticate_user!

  private

  def authenticate_user!
    if !authorized_user?
      render 'auth/notify'
    end
  end

  def authorized_user?
    if request.env['omniauth.auth']
      email = request.env['omniauth.auth'][:info][:email]
      return true if email.index( /@8thlight\.com$/ )
    elsif session[:user_id]
      user = Dojo::Repository.user.find( session[:user_id] )
      return true if user
    end

    return false
  end

end

app/controllers/feedback_controller.rb
require 'dojo/models/feedback'
require 'dojo/repositories/repository'
require 'dojo/validation/feedback_validator'

class FeedbackController < AuthorizedController

  def create
    kata_id = params[:kata_id]
    with_user = params.merge( user: session[:user_id] )

    if Dojo::FeedbackValidator.valid?( with_user )
      create_feedback( with_user )
    else
      fields = Dojo::Feedback.attributes
      flash[:form_values] = symbolize_keys( params ).
        select { |k,v| fields.include? k }
      flash[:errors] = Dojo::FeedbackValidator.errors( params )
    end

    redirect_to kata_path( kata_id )
  end

  private

  def create_feedback( params )
    repo = Dojo::Repository.feedback
    repo.save( repo.new( params ))
  end

end

app/controllers/katas_controller.rb
require 'dojo/repositories/repository'
require 'dojo/presenters/kata_presenter'
require 'dojo/validation/kata_validator'
require 'dojo/services/media_service'
require 'dojo/services/vimeo_service'
require 'uri'

class KatasController < AuthorizedController

  def show
    kata = repo.kata.find( params[:id] )
    @kata = Dojo::KataPresenter.new( kata )
    feedback = repo.feedback.find_by_kata_id( params[:id] )
    @feedback = feedback.map { |fb| Dojo::FeedbackPresenter.new( fb ) }
    uri = URI.parse( @kata.link )
    @editable = ( kata.user == session[:user_id] )
    @video = Dojo::MediaService.embed( uri )
    @partial = embed_partial_for( @video )
    @form_values = flash[:form_values] || {}
    @errors = flash[:errors] || {}
  end

  def new
    @form_values = flash[:form_values] || {}
    @errors = flash[:errors] || {}
    render :new
  end

  def edit
    kata = repo.kata.find( params[:id] )
    kata_values = { id:          kata.id,
                    title:       kata.title,
                    link:        kata.link,
                    description: kata.description }
    @form_values = flash[:form_values] || kata_values
    @errors = flash[:errors] || {}
    render :edit
  end

  def create
    if Dojo::KataValidator.valid?( params )
      params.update( user: session[:user_id] )
      kata = repo.kata.save(repo.kata.new( params ))
      redirect_to kata_path( kata.id )
    else
      fields = Dojo::Kata.attributes
      flash[:form_values] = symbolize_keys( params ).
        select { |k,v| fields.include? k }
      flash[:errors] = Dojo::KataValidator.errors( params )
      redirect_to new_kata_path
    end
  end

  def update
    if Dojo::KataValidator.valid?( params )
      kata = repo.kata.find( params[:id] )
      kata = repo.kata.save( kata.update( params ) )
      redirect_to kata_path( kata.id )
    else
      fields = Dojo::Kata.attributes
      flash[:form_values] = symbolize_keys( params ).
        select { |k,v| fields.include? k }
      flash[:errors] = Dojo::KataValidator.errors( params )
      redirect_to edit_kata_path( params[:id] )
    end
  end

  def index
    katas = repo.kata.sort
    @katas = katas.map { |kata| Dojo::KataPresenter.new( kata ) }
    render :index
  end

  private

  def repo
    Dojo::Repository
  end

  def embed_partial_for( video )
    case video
    when Dojo::Media::VimeoVideo
      'vimeo'
    when Dojo::Media::YouTubeVideo
      'youtube'
    else
      'broken_embed'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "Dojo"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

end

app/helpers/dojo_helper.rb
module DojoHelper

  def current_user
    if session[:user_id]
      @current_user ||= Dojo::Repository.user.find( session[:user_id] )
    end
  end

end

app/helpers/katas_helper.rb
module KatasHelper
    
    def timestamp(timestamp)
      timestamp.strftime('%B %-d, %Y at %l:%M%P')
    end

    def feedback_header(count)
      if (count < 5)
        "This kata needs your feedback. Share your thoughts!"
      else
        "Learn what makes a great kata. Share with feedback!"
      end
    end

    def form_field_value(id, values)
      values[id] if (values && values[id])
    end

    def form_error_highlights(id, errors, options={})
      options[:class] = 'error_highlight' if (errors && errors[id])
      options
    end

    def form_error_message(id, errors)
      if has_errors(id, errors)
        content_tag(:span, errors[id], :class => "error_message")
      end
    end

    def has_errors(id, errors)
      errors && errors[id]
    end

    def f_error_message(message)
      if message
        content_tag(:span, message, :class => "error_message")
      end
    end

    def scale_to_width(dimensions, width)
      scale = width.to_f / dimensions[:width]
      { width: width, height: (dimensions[:height] * scale).to_i }
    end

end

app/helpers/timestamp_helper.rb
module TimestampHelper

  def datetime_to_date_and_time(datetime)
    datetime.strftime('%B %-d, %Y at %l:%M%P')
  end

end

app/views/katas/_broken_embed.html.erb
<div id="embed_broken">
  <h3>This video does not exist</h3>
</div>

app/views/katas/_form.html.erb
<%= form_tag action, { :method => method || 'post' } do %>

  <div class='control-group'>
    <%= label_tag :title, "Title", :class => 'control-label' %>
    <div class='controls'>
      <%= text_field_tag :title, @form_values[:title],
        form_error_highlights(:title, @errors) %>
        <%= f_error_message(@errors[:title]) %>
    </div>
  </div>

  <div class='control-group'>
    <%= label_tag :link, "Link", :class => 'control-label' %>
    <div class='controls'>
      <%= text_field_tag :link, @form_values[:link],
        form_error_highlights(:link, @errors) %>
        <%= f_error_message(@errors[:link]) %>
    </div>
  </div>

  <div class='control-group'>
    <%= label_tag :description, "Description", :class => 'control-label' %>
    <div class='controls'>
      <%= text_area_tag :description, @form_values[:description],
        form_error_highlights(:description, @errors, {:rows => 4}) %>
        <%= f_error_message(@errors[:description]) %>
    </div>
  </div>

  <div class='control-group'>
    <div class='controls'>
      <%= submit_tag "Submit", :class => 'btn' %>
    </div>
  </div>

<% end %>

app/views/katas/_vimeo.html.erb
<div>
  <iframe src="http://player.vimeo.com/video/<%= @video.id %>?title=0&amp;byline=0&amp;portrait=0" width="720" height="<%= scale_to_width({ width: @video.width, height: @video.height }, 720)[:height] %>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
</div> 

app/views/katas/_youtube.html.erb
<div>
  <iframe width="720" height="405" src="http://www.youtube.com/embed/<%= @video.id %>" frameborder="0" allowfullscreen></iframe>
</div>

app/views/katas/edit.html.erb
<h2>Edit this Kata</h2>

<div class="kata_form">
  <%= render :partial => 'form', :locals => { :method => 'put', :action => ('/katas/' + @form_values[:id].to_s) } %>
</div>

app/views/katas/index.html.erb
<h3>Available Katas</h3>

<table class='table clickable_rows'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Last Update</th>
    </tr>
  </thead>

  <tbody>

    <% @katas.each do |kata| %>
      <tr data-href='<%= kata_path( kata.id ) %>'>
        <td><%= kata.title %></td>
        <td><%= kata.user_name %></td>
        <td><%= datetime_to_date_and_time( kata.updated_at ) %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/katas/new.html.erb
<h2>Create a Kata</h1>

<div class="kata_form">
  <%= render :partial => 'form', :locals => { :method => 'post', :action => '/katas/' } %>
</div>

app/views/katas/show.html.erb
<div class="kata_container">

  <div class="header">
    <h2><%= @kata.title %></h2>
    <% if @editable %>
      <span class="edit_link"><%= link_to "edit", edit_kata_path( @kata.id ) %></span>
    <% end %>
  </div>

  <div class="video_container">
    <%= render :partial => @partial %>
  </div>

  <div class="description">
    <p class="description">
    <% @kata.description.split( /\r\n|\n/ ).each do |section| %>
      <%= section %><br/>
    <% end %>
    <p class="user">Created by <%= @kata.user_name %></p>
    <p class="timestamp">Last updated on <%= timestamp( @kata.updated_at ) %></p>
    </p>
  </div>

</div>

<div class="kata_supplements">
  <h3><%= feedback_header( @feedback.size ) %></h3>
  <% if ( @feedback.size > 0 ) %>
    <div class="feedback_stream">
      <% @feedback.each do |feedback| %>
        <div class="feedback_container">
          <p class="message"><%= feedback.message %></p>
          <p class="timestamp">Submitted by <%= feedback.user_name %>
            on <%= timestamp( feedback.created_at ) %></p>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="feedback_form">
    <%= form_tag '/feedback', :class => 'form' do %>
      <%= hidden_field_tag :kata_id, @kata.id %>
      <%= text_area_tag :message, "", form_error_highlights( :message, @errors, :placeholder => "Leave some feedback" ) %>
      <%= f_error_message( @errors[:message] ) %>
      <%= submit_tag "Submit", :class => 'btn' %>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div id="header">
      <div class="inner">
        <h1 id="logo"><%= link_to "DOJO", root_url %></h1>
        <div id="quicklinks">
          <% if current_user %>
            <span>Greetings, <%= current_user.name %>!</span>
            <%= link_to "Create a Kata", new_kata_url, {:class => "btn"} %>
            <%= link_to "Sign out", signout_path, {:class => "btn"} %>
          <% else %>
            <span>Greetings, guest!</span>
            <%= link_to "Sign in", "/auth/google_oauth2/", {:class => "btn"} %>
          <% end %>
        </div>
      </div>
    </div>

    <div id="main">

      <%= yield %>

    </div>
  </body>
</html>